/* ============================================================
   Config — edit this file to customize the site.
   ============================================================ */

// Your GitHub username.
const GITHUB_USER = "kutaygunal";

// Profile — powers the header nameplate, hero readout, and contact panel.
const PROFILE = {
  name: "Kutay Gunal",
  handle: "kutaygunal",
  role: "lead_software_engineer @ siemens",
  focus: "simulation platforms · AI-driven tooling",
  location: "Fort Lauderdale, FL",
  status: "OPERATIONAL",
  bio:
    "By day: C++/Qt simulation platforms and AI-driven engineering tools at Siemens. " +
    "By night: whatever's interesting enough to keep me up — parsers, compression, " +
    "flight software, the occasional habit tracker. Logged here as they ship.",
  yearsExperience: 10,
  stack: ["C++", "Qt", "Python", ".NET", "C#", "OpenCascade", "LLM/AI"],
  email: "kutaygunal@outlook.com",
  github: "https://github.com/kutaygunal",
  linkedin: "https://www.linkedin.com/in/kutaygunal/",
};

// Curated project data for the showcase.
// Fields: name (repo), title (display name), description, url, language,
//   tags[], featured (bool), status, category (drives the spec-sheet icon).
const PROJECTS = [
  {
    name: "LuxTrace",
    title: "LuxTrace",
    description: "Optical Design Studio: desktop C++ application for optical and illumination design built on OpenCASCADE and Qt 6. Builds optical geometry as B-Rep solids, runs a Monte Carlo ray trace, and reports irradiance maps, far-field intensity, spot metrics, energy budget, and error bars. C++20, Qt 6.8, OCCT 7.8.",
    url: "https://github.com/kutaygunal/LuxTrace",
    language: "C++",
    tags: ["Systems", "Optics", "OCCT"],
    featured: true,
    status: "SHIPPED",
    category: "systems",
  },
  {
    name: "AEGIS-PERC",
    title: "Aegis Perc",
    description: "C++/Qt platform for semiconductor electrical rule verification and signoff.",
    url: "https://github.com/kutaygunal/AEGIS-PERC",
    language: "C++",
    tags: ["Systems"],
    featured: true,
    status: "SHIPPED",
    category: "systems",
  },
  {
    name: "kzip",
    title: "Kzip",
    description: "High-performance compression tool that builds fast, drop-in-compatible ZIPs in Rust.",
    url: "https://github.com/kutaygunal/kzip",
    language: "Rust",
    tags: ["Systems", "Compression"],
    featured: true,
    status: "SHIPPED",
    category: "compression",
  },
  {
    name: "LaTeXOCR",
    title: "LaTeX OCR",
    description: "Converts images of LaTeX into LaTeX text using a vision-language model.",
    url: "https://github.com/kutaygunal/LaTeXOCR",
    language: "Python",
    tags: ["AI", "OCR", "LaTeX"],
    featured: true,
    status: "SHIPPED",
    category: "ai",
  },
  {
    name: "OptiForge",
    title: "OptiForge",
    description: "AI-powered generative lens design: turn focal length, pupil, field, and waveband specs into a ranked set of viable starting-point lens sequences.",
    url: "https://github.com/kutaygunal/OptiForge",
    language: "Python",
    tags: ["AI", "Optics", "Generative"],
    featured: true,
    status: "SHIPPED",
    category: "ai",
  },
  {
    name: "CSV-Arrow-Parser",
    title: "Csv Arrow Parser",
    description: "GPU-accelerated CUDA parser that turns CSV into typed columnar buffers at 4 GB/s.",
    url: "https://github.com/kutaygunal/CSV-Arrow-Parser",
    language: "C++",
    tags: ["Systems", "Data"],
    featured: true,
    status: "SHIPPED",
    category: "data",
  },
  {
    name: "CodeBaseQA",
    title: "CodeBase QA",
    description: "Code-centric codebase QA assistant: answers natural-language questions about a real C++ codebase using AST-aware chunking, hybrid retrieval (BM25 + embeddings), a symbol index, and agentic tool use. Every answer is grounded with clickable path:line citations. Ships a CLI and a full-featured web chat UI.",
    url: "https://github.com/kutaygunal/CodeBaseQA",
    language: "Python",
    tags: ["AI", "RAG", "Codebase"],
    featured: true,
    status: "SHIPPED",
    category: "ai",
  },
  {
    name: "LodeStar",
    title: "LodeStar",
    description: "Automated GNSS/SBAS integrated test and verification platform with DO-178C compliance, C++/Qt.",
    url: "https://github.com/kutaygunal/LodeStar",
    language: "C++",
    tags: ["Systems", "GNSS"],
    status: "SHIPPED",
    category: "telemetry",
  },
  {
    name: "PatchOrchestrator",
    title: "Patch Orchestrator",
    description: "C++/Qt control plane for scheduling, pausing, and rolling back fleet-wide software patches.",
    url: "https://github.com/kutaygunal/PatchOrchestrator",
    language: "C++",
    tags: ["Systems", "Fleet"],
    featured: true,
    status: "SHIPPED",
    category: "systems",
  },
  {
    name: "healthcare-revenue-risk-predictor",
    title: "Healthcare Revenue Risk Predictor",
    description: "ML model + interactive dashboard to predict healthcare revenue risk.",
    url: "https://github.com/kutaygunal/healthcare-revenue-risk-predictor",
    language: "Python",
    tags: ["ML", "Dashboard", "Data"],
    featured: true,
    status: "SHIPPED",
    category: "ai",
  },
  {
    name: "Aegis-GCS",
    title: "Aegis Gcs",
    description: "C++/Qt ground control station for UAS telemetry, mission planning, and live visualization.",
    url: "https://github.com/kutaygunal/Aegis-GCS",
    language: "C++",
    tags: ["Systems"],
    status: "SHIPPED",
    category: "telemetry",
  },
  {
    name: "AeroVerify",
    title: "Aero Verify",
    description: "C#/Python workbench that validates and verifies modular avionics configurations.",
    url: "https://github.com/kutaygunal/AeroVerify",
    language: "C#",
    tags: [".NET", "Desktop"],
    status: "SHIPPED",
    category: "desktop",
  },
  {
    name: "VistaCAD",
    title: "Vista Cad",
    description: "Qt 6 / OpenCASCADE 3D viewer for interactive geometric modeling of process-plant components.",
    url: "https://github.com/kutaygunal/VistaCAD",
    language: "C++",
    tags: ["Systems", "3D"],
    status: "SHIPPED",
    category: "3d",
  },
  {
    name: "habit_coin",
    title: "Habit Coin",
    description: "Web app for tracking daily habits and building consistent routines.",
    url: "https://github.com/kutaygunal/habit_coin",
    language: "HTML",
    tags: ["Web", "Productivity"],
    status: "SHIPPED",
    category: "productivity",
  },
  {
    name: "cpp-interview-prep",
    title: "C++ Interview Quest",
    description: "Gamified C++ interview prep: battle through OOP, data structures, modern C++, design patterns, and interview Q&A worlds. Earn XP, build combos, beat boss questions.",
    url: "/cpp-interview-prep/",
    language: "JavaScript",
    tags: ["C++", "Interview", "Game"],
    status: "SHIPPED",
    category: "game",
  },
  {
    name: "BookTranslator",
    title: "Book Translator",
    description: "Desktop tool that translates books into 15 languages privately with local AI.",
    url: "https://github.com/kutaygunal/BookTranslator",
    language: "C#",
    tags: [".NET", "Desktop", "AI"],
    status: "SHIPPED",
    category: "ai",
  },
  {
    name: "SocialOwls",
    title: "Social Owls",
    description: "Angular course project for learning the Angular framework.",
    url: "https://github.com/kutaygunal/SocialOwls",
    language: "JavaScript",
    tags: ["Web", "Angular"],
    status: "SHIPPED",
    category: "component",
  },
  {
    name: "dark-mode-icon-enhancer",
    title: "Dark Mode Icon Enhancer",
    description: "Desktop app that converts dark icons to be more visible in dark mode.",
    url: "https://github.com/kutaygunal/dark-mode-icon-enhancer",
    language: "Python",
    tags: ["Desktop", "Tools"],
    status: "SHIPPED",
    category: "desktop",
  },
  {
    name: "ArcanovaLabs",
    title: "Arcanova Labs",
    description: "Astro + Cloudflare marketing site for the Arcanova Labs app & web studio — projects, privacy policy, and a bold app/web portfolio shell.",
    url: "https://github.com/kutaygunal/ArcanovaLabs",
    language: "HTML",
    tags: ["Web", "Astro"],
    status: "SHIPPED",
    category: "component",
  },
  {
    name: "Posturist-Website",
    title: "Posturist Website",
    description: "Modern posture training app with a 21-day program, guided workouts, and progress tracking.",
    url: "https://github.com/kutaygunal/Posturist-Website",
    language: "HTML",
    tags: ["Web", "Health"],
    status: "SHIPPED",
    category: "health",
  },
  {
    name: "NASA_API",
    title: "Nasa Api",
    description: "Web app that pulls data from NASA's public API.",
    url: "https://github.com/kutaygunal/NASA_API",
    language: "JavaScript",
    tags: ["Web", "API"],
    status: "SHIPPED",
    category: "api",
  },
  {
    name: "sorting-algorithm-visualizer",
    title: "Sorting Algorithm Visualizer",
    description: "Interactive web app that visualizes sorting algorithms in real time.",
    url: "https://github.com/kutaygunal/sorting-algorithm-visualizer",
    language: "JavaScript",
    tags: ["Web", "Visualization"],
    status: "SHIPPED",
    category: "visualization",
  },
  {
    name: "SubeSabir-EksiTatli",
    title: "Sube Sabir Eksi Tatli",
    description: "Godot 4 party game built in GDScript — scripted dialogs, a rating indicator, custom UI, sounds, and a gamescene.",
    url: "https://github.com/kutaygunal/SubeSabir-EksiTatli",
    language: "GDScript",
    tags: ["Game", "Godot"],
    status: "SHIPPED",
    category: "game",
  },
  {
    name: "Koroghlu",
    title: "Koroghlu",
    description: "C# game development project — Koroghlu, built with the .NET/Unity toolchain.",
    url: "https://github.com/kutaygunal/Koroghlu",
    language: "C#",
    tags: ["Game", "C#"],
    status: "SHIPPED",
    category: "game",
  },
];
