/* ============================================================
   Config — edit this file to customize the site.
   ============================================================ */

// Your GitHub username (used by the live dashboard).
const GITHUB_USER = "kutaygunal";

// Curated project data for the showcase.
// Add/remove entries here. Fields:
//   name (repo name, used by dashboard), title (display name),
//   description, url, language, tags[], featured (bool)
const PROJECTS = [
  {
    name: "healthcare-revenue-risk-predictor",
    title: "Healthcare Revenue Risk Predictor",
    description: "ML model + interactive dashboard to predict healthcare revenue risk.",
    url: "https://github.com/kutaygunal/healthcare-revenue-risk-predictor",
    language: "Python",
    tags: ["ML", "Dashboard", "Data"],
    featured: true,
    image: "assets/card_ml.png",
  },
  {
    name: "kzip",
    title: "Kzip",
    description: "High-performance compression tool that builds fast, drop-in-compatible ZIPs in Rust.",
    url: "https://github.com/kutaygunal/kzip",
    language: "Rust",
    tags: ["Systems", "Compression"],
    featured: true,
    image: "assets/card_zip.png",
  },
  {
    name: "CSV-Arrow-Parser",
    title: "Csv Arrow Parser",
    description: "GPU-accelerated CUDA parser that turns CSV into typed columnar buffers at 4 GB/s.",
    url: "https://github.com/kutaygunal/CVS-Arrow-Parser",
    language: "C++",
    tags: ["Systems", "Data"],
    featured: true,
    image: "assets/card_csv.png",
  },
  {
    name: "AEGIS-PERC",
    title: "Aegis Perc",
    description: "C++/Qt platform for semiconductor electrical rule verification and signoff.",
    url: "https://github.com/kutaygunal/AEGIS-PERC",
    language: "C++",
    tags: ["Systems"],
    image: "assets/card_aegis.png",
  },
  {
    name: "Aegis-GCS",
    title: "Aegis Gcs",
    description: "C++/Qt ground control station for UAS telemetry, mission planning, and live visualization.",
    url: "https://github.com/kutaygunal/Aegis-GCS",
    language: "C++",
    tags: ["Systems"],
    image: "assets/card_gcs.png",
  },
  {
    name: "AeroVerify",
    title: "Aero Verify",
    description: "C#/Python workbench that validates and verifies modular avionics configurations.",
    url: "https://github.com/kutaygunal/AeroVerify",
    language: "C#",
    tags: [".NET", "Desktop"],
    image: "assets/card_aero.png",
  },
  {
    name: "BookTranslator",
    title: "Book Translator",
    description: "Desktop tool that translates books into 15 languages privately with local AI.",
    url: "https://github.com/kutaygunal/BookTranslator",
    language: "C#",
    tags: [".NET", "Desktop", "AI"],
    image: "assets/card_book.png",
  },
  {
    name: "sorting-algorithm-visualizer",
    title: "Sorting Algorithm Visualizer",
    description: "Interactive web app that visualizes sorting algorithms in real time.",
    url: "https://github.com/kutaygunal/sorting-algorithm-visualizer",
    language: "JavaScript",
    tags: ["Web", "Visualization"],
    image: "assets/card_sort.png",
  },
  {
    name: "habit_coin",
    title: "Habit Coin",
    description: "Web app for tracking daily habits and building consistent routines.",
    url: "https://github.com/kutaygunal/habit_coin",
    language: "HTML",
    tags: ["Web", "Productivity"],
    image: "assets/card_habit.png",
  },
  {
    name: "dark-mode-icon-enhancer",
    title: "Dark Mode Icon Enhancer",
    description: "Desktop app that converts dark icons to be more visible in dark mode.",
    url: "https://github.com/kutaygunal/dark-mode-icon-enhancer",
    language: "Python",
    tags: ["Desktop", "Tools"],
    image: "assets/card_dark.png",
  },
  {
    name: "NASA_API",
    title: "Nasa Api",
    description: "Web app that pulls data from NASA's public API.",
    url: "https://github.com/kutaygunal/NASA_API",
    language: "JavaScript",
    tags: ["Web", "API"],
    image: "assets/card_nasa.png",
  },
  {
    name: "Posturist-Website",
    title: "Posturist Website",
    description: "Modern posture training app with a 21-day program, guided workouts, and progress tracking.",
    url: "https://github.com/kutaygunal/Posturist-Website",
    language: "HTML",
    tags: ["Web", "Health"],
    image: "assets/card_posturist.png",
  },
  {
    name: "VistaCAD",
    title: "Vista Cad",
    description: "Qt 6 / OpenCASCADE 3D viewer for interactive geometric modeling of process-plant components.",
    url: "https://github.com/kutaygunal/VistaCAD",
    language: "C++",
    tags: ["Systems", "3D"],
    image: "assets/card_vista.png",
  },
  {
    name: "SocialOwls",
    title: "Social Owls",
    description: "Angular course project for learning the Angular framework.",
    url: "https://github.com/kutaygunal/SocialOwls",
    language: "JavaScript",
    tags: ["Web", "Angular"],
    image: "assets/card_owls.png",
  },
];
