/* ============================================================
   C++ Interview Quest — question bank
   Each world = one study topic. Each question:
     { q, options[4], answer (index), explain }
   Boss questions are harder, worth more XP.
   ============================================================ */

const WORLDS = [
  {
    id: "oop",
    name: "Object-Oriented Principles",
    icon: "◆",
    tagline: "Encapsulation, inheritance, polymorphism, abstraction.",
    color: "#4fc3f7",
    questions: [
      {
        q: "Which OOP principle hides internal state and only exposes it through public methods?",
        options: ["Inheritance", "Encapsulation", "Polymorphism", "Abstraction"],
        answer: 1,
        explain: "Encapsulation bundles data with the methods that operate on it and restricts direct access to that data, usually via private members and public accessors.",
      },
      {
        q: "What is the difference between a class and a struct in C++?",
        options: [
          "Structs cannot have methods",
          "Default access: struct members are public, class members are private",
          "Classes cannot be instantiated on the stack",
          "There is no difference",
        ],
        answer: 1,
        explain: "The only default difference is access control: struct defaults to public, class defaults to private. Both can have methods, constructors, and inheritance.",
      },
      {
        q: "Which keyword prevents a class from being inherited?",
        options: ["static", "const", "final", "sealed"],
        answer: 2,
        explain: "In C++11+, marking a class 'final' prevents it from being used as a base class. (C# uses 'sealed'; C++ uses 'final'.)",
      },
      {
        q: "What is a virtual destructor and why is it important?",
        options: [
          "It makes the destructor inline",
          "It ensures the derived class destructor runs when deleting through a base pointer",
          "It prevents the destructor from being called",
          "It is required for all classes",
        ],
        answer: 1,
        explain: "When you delete a derived object through a base-class pointer, a non-virtual destructor causes undefined behavior. A virtual destructor ensures the correct derived destructor runs.",
      },
      {
        q: "What does 'pure virtual' mean, and what does it make a class?",
        options: [
          "A function with no body; makes the class abstract",
          "A function that cannot be overridden",
          "A static member function",
          "A function that returns void",
        ],
        answer: 0,
        explain: "A pure virtual function (declared with '= 0') has no definition in the base class. A class with at least one pure virtual function is abstract and cannot be instantiated.",
      },
      {
        q: "Which access specifier makes members visible to derived classes but not to the outside world?",
        options: ["public", "private", "protected", "friend"],
        answer: 2,
        explain: "'protected' members are accessible within the class and by derived classes, but not by external code.",
      },
      {
        q: "What is the 'diamond problem' in multiple inheritance?",
        options: [
          "A class inheriting from two classes that share a common base, causing ambiguity",
          "A class with too many methods",
          "A circular dependency between two classes",
          "A memory leak in inheritance",
        ],
        answer: 0,
        explain: "If B and C both inherit from A, and D inherits from both B and C, D has two copies of A. 'virtual inheritance' solves this by sharing a single A subobject.",
      },
      {
        q: "What is the difference between overloading and overriding?",
        options: [
          "They are the same thing",
          "Overloading: same name, different params (compile-time). Overriding: redefining a virtual function in a derived class (runtime)",
          "Overriding changes the return type only",
          "Overloading only works with operators",
        ],
        answer: 1,
        explain: "Overloading is compile-time polymorphism (same name, different signatures). Overriding is runtime polymorphism via virtual functions in a derived class.",
      },
      {
        q: "What is the purpose of the 'friend' keyword?",
        options: [
          "It makes a class public",
          "It grants a function or class access to private/protected members",
          "It creates a copy of a class",
          "It marks a class as thread-safe",
        ],
        answer: 1,
        explain: "A friend function or friend class can access the private and protected members of the class that declares it as a friend. It breaks encapsulation deliberately.",
      },
      {
        q: "What is the difference between composition and inheritance?",
        options: [
          "Composition is 'has-a', inheritance is 'is-a'",
          "Inheritance is 'has-a', composition is 'is-a'",
          "They are identical",
          "Composition cannot be used in C++",
        ],
        answer: 0,
        explain: "Composition models a 'has-a' relationship (a Car has an Engine). Inheritance models an 'is-a' relationship (a Dog is an Animal). Prefer composition over inheritance when possible.",
      },
    ],
    boss: {
      q: "Explain the full object lifetime of 'Base* b = new Derived();' — construction order, destruction order, and what happens if the destructor is not virtual.",
      options: [
        "Base ctor, then Derived ctor; Derived dtor, then Base dtor; non-virtual dtor = undefined behavior",
        "Derived ctor, then Base ctor; Base dtor, then Derived dtor; always safe",
        "Only Derived ctor runs; only Base dtor runs; always safe",
        "Base ctor, then Derived ctor; Base dtor, then Derived dtor; always safe",
      ],
      answer: 0,
      explain: "Construction runs base-first, then derived. Destruction runs derived-first, then base. Deleting through a base pointer with a non-virtual destructor is undefined behavior — the derived destructor never runs.",
    },
  },
  {
    id: "ds",
    name: "Data Structures",
    icon: "▤",
    tagline: "Containers, complexity, and when to use what.",
    color: "#81c784",
    questions: [
      {
        q: "What is the average time complexity of std::vector::push_back?",
        options: ["O(1) amortized", "O(n)", "O(log n)", "O(n²)"],
        answer: 0,
        explain: "push_back is O(1) amortized: occasional reallocation costs O(n), but averaged over many insertions it is constant time.",
      },
      {
        q: "Which container is best for frequent insertions/deletions in the middle?",
        options: ["std::vector", "std::list", "std::array", "std::string"],
        answer: 1,
        explain: "std::list (doubly-linked list) supports O(1) insertion/deletion at a known position. std::vector requires shifting elements (O(n)).",
      },
      {
        q: "What is the time complexity of a std::map lookup?",
        options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
        answer: 2,
        explain: "std::map is a balanced binary search tree (typically red-black), so lookups are O(log n). std::unordered_map gives O(1) average.",
      },
      {
        q: "What is the difference between std::map and std::unordered_map?",
        options: [
          "map is sorted (O(log n)), unordered_map is hash-based (O(1) average)",
          "map is faster than unordered_map always",
          "unordered_map is always sorted",
          "There is no difference",
        ],
        answer: 0,
        explain: "std::map is a sorted tree (O(log n) ops, ordered iteration). std::unordered_map is a hash table (O(1) average ops, no ordering).",
      },
      {
        q: "What is the time complexity of std::sort on a random-access container?",
        options: ["O(n)", "O(n log n)", "O(log n)", "O(n²)"],
        answer: 1,
        explain: "std::sort is introsort, a hybrid of quicksort/heapsort/insertion sort, giving O(n log n) average and worst case.",
      },
      {
        q: "Which data structure is a std::priority_queue built on?",
        options: ["A linked list", "A hash table", "A binary heap", "A balanced tree"],
        answer: 2,
        explain: "std::priority_queue is a max-heap (by default) implemented as a binary heap over a vector. push/pop are O(log n), top is O(1).",
      },
      {
        q: "What is the difference between a stack and a queue?",
        options: [
          "Stack is LIFO, queue is FIFO",
          "Stack is FIFO, queue is LIFO",
          "They are identical",
          "Stack is sorted, queue is not",
        ],
        answer: 0,
        explain: "A stack is Last-In-First-Out (push/pop at the top). A queue is First-In-First-Out (enqueue at back, dequeue at front).",
      },
      {
        q: "What is the time complexity of searching for an element in a sorted std::vector using std::binary_search?",
        options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
        answer: 2,
        explain: "std::binary_search on a sorted random-access range is O(log n) using binary search.",
      },
      {
        q: "What is the main advantage of a std::deque over a std::vector?",
        options: [
          "O(1) insertion at both the front and back",
          "It is always sorted",
          "It uses less memory",
          "It is thread-safe",
        ],
        answer: 0,
        explain: "std::deque supports O(1) push/pop at both ends, unlike vector which is O(n) for front insertion. It is implemented as a sequence of fixed-size blocks.",
      },
      {
        q: "What is the time complexity of std::unordered_map::find in the average case?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
        answer: 0,
        explain: "A hash table gives O(1) average-case lookup. Worst case (many collisions) degrades to O(n), but with a good hash it is effectively constant.",
      },
    ],
    boss: {
      q: "You need a container that supports O(1) average lookup by key AND preserves insertion order. Which standard container do you choose, and what is the trade-off?",
      options: [
        "std::map — it preserves order and gives O(log n) lookup",
        "std::unordered_map — O(1) lookup, but it does NOT preserve insertion order",
        "std::vector of pairs — O(1) lookup and preserves order",
        "std::list — O(1) lookup and preserves order",
      ],
      answer: 1,
      explain: "No single standard container gives both. std::unordered_map gives O(1) average lookup but no ordering. To preserve insertion order you must pair it with a separate ordered structure (e.g., a vector of keys) or use a custom 'ordered map'.",
    },
  },
  {
    id: "modern",
    name: "Modern C++",
    icon: "⚡",
    tagline: "C++11/14/17/20: smart pointers, move semantics, lambdas.",
    color: "#ffd54f",
    questions: [
      {
        q: "What is the difference between std::unique_ptr and std::shared_ptr?",
        options: [
          "unique_ptr has exclusive ownership; shared_ptr uses reference counting",
          "shared_ptr is exclusive; unique_ptr is shared",
          "They are identical",
          "unique_ptr cannot be used with new",
        ],
        answer: 0,
        explain: "std::unique_ptr has exclusive ownership (cannot be copied, only moved). std::shared_ptr uses reference counting so multiple owners share the object; it is destroyed when the last owner releases it.",
      },
      {
        q: "What does std::move do?",
        options: [
          "It copies an object",
          "It casts an lvalue to an rvalue reference, enabling move semantics",
          "It deletes an object",
          "It allocates memory",
        ],
        answer: 1,
        explain: "std::move is a cast to an rvalue reference. It does not move anything itself — it makes an object eligible to be moved-from by move constructors/assignment operators.",
      },
      {
        q: "What is a lambda expression?",
        options: [
          "A named function",
          "An anonymous function object that can capture variables from its scope",
          "A macro",
          "A template",
        ],
        answer: 1,
        explain: "A lambda is an anonymous function object. It can capture variables by value [=] or by reference [&], and is often used with STL algorithms.",
      },
      {
        q: "What is the difference between 'auto' and 'decltype'?",
        options: [
          "auto deduces from the initializer; decltype deduces the declared type of an expression",
          "They are identical",
          "decltype is only for functions",
          "auto is only for loops",
        ],
        answer: 0,
        explain: "'auto' deduces the type from the initializer expression. 'decltype' inspects the declared type of an expression without evaluating it, preserving references and const.",
      },
      {
        q: "What is a move constructor and when is it called?",
        options: [
          "It copies an object; called on assignment",
          "It transfers resources from a temporary; called when moving an rvalue",
          "It deletes an object; called on destruction",
          "It is the same as a copy constructor",
        ],
        answer: 1,
        explain: "A move constructor transfers ownership of resources (e.g., a heap buffer) from a temporary rvalue, avoiding a deep copy. It is called when constructing from an rvalue (e.g., std::move or a returned temporary).",
      },
      {
        q: "What is the Rule of Five?",
        options: [
          "A class should have at most five members",
          "If you define one of destructor/copy ctor/copy assign/move ctor/move assign, you should define all five",
          "A function can have five parameters",
          "A class can inherit from five bases",
        ],
        answer: 1,
        explain: "The Rule of Five states that if a class manages a resource and you define any of the destructor, copy constructor, copy assignment, move constructor, or move assignment, you should define all five to manage the resource correctly.",
      },
      {
        q: "What is std::optional used for?",
        options: [
          "Storing a value that may or may not be present",
          "Storing multiple values",
          "Making a value constant",
          "Storing a function",
        ],
        answer: 0,
        explain: "std::optional<T> represents a value that may or may not exist. It is a safer alternative to returning a sentinel or a pointer that may be null.",
      },
      {
        q: "What is a variadic template?",
        options: [
          "A template with a fixed number of parameters",
          "A template that accepts a variable number of arguments (parameter pack)",
          "A template that returns void",
          "A template that cannot be instantiated",
        ],
        answer: 1,
        explain: "A variadic template uses a parameter pack (e.g., template<typename... Args>) to accept any number of arguments. It is the basis of std::tuple and perfect forwarding.",
      },
      {
        q: "What is the purpose of 'constexpr'?",
        options: [
          "To make a variable mutable",
          "To evaluate a function or variable at compile time",
          "To make a function inline",
          "To declare a global constant",
        ],
        answer: 1,
        explain: "'constexpr' tells the compiler a value or function can be evaluated at compile time, enabling compile-time computation and better optimization.",
      },
      {
        q: "What is structured binding (C++17)?",
        options: [
          "A way to bind a struct to a class",
          "A way to decompose a tuple/struct into named variables",
          "A way to bind a reference",
          "A way to create a new struct",
        ],
        answer: 1,
        explain: "Structured bindings (auto [a, b] = pair;) decompose a tuple, pair, or struct into individual named variables in one declaration.",
      },
    ],
    boss: {
      q: "What is perfect forwarding and what is the role of std::forward?",
      options: [
        "std::forward casts to an lvalue; perfect forwarding copies arguments",
        "std::forward preserves the value category of arguments so they are forwarded exactly; used with forwarding references (T&&)",
        "std::forward deletes arguments",
        "std::forward is the same as std::move",
      ],
      answer: 1,
      explain: "Perfect forwarding passes arguments to another function preserving their value category (lvalue vs rvalue). std::forward, used with a forwarding reference (T&&), conditionally casts to an rvalue only when the original was an rvalue.",
    },
  },
  {
    id: "patterns",
    name: "Design Patterns",
    icon: "◈",
    tagline: "Singleton, Factory, Observer, Strategy, RAII, and more.",
    color: "#f48fb1",
    questions: [
      {
        q: "What is the Singleton pattern?",
        options: [
          "A class that can be instantiated many times",
          "A class that ensures only one instance exists and provides a global access point",
          "A class with no methods",
          "A class that cannot be inherited",
        ],
        answer: 1,
        explain: "Singleton restricts a class to a single instance and provides a global access point. In C++11+, a function-local static is thread-safe and is the preferred implementation.",
      },
      {
        q: "What is the Factory pattern used for?",
        options: [
          "Creating objects without specifying their concrete class",
          "Destroying objects",
          "Sorting objects",
          "Copying objects",
        ],
        answer: 0,
        explain: "The Factory pattern centralizes object creation, letting a client create objects through an interface without knowing the concrete class. It decouples creation from use.",
      },
      {
        q: "What is the Observer pattern?",
        options: [
          "A pattern where one object notifies dependents of state changes",
          "A pattern for sorting data",
          "A pattern for memory management",
          "A pattern for creating singletons",
        ],
        answer: 0,
        explain: "The Observer pattern defines a one-to-many dependency: when the subject changes state, all registered observers are notified automatically. It is common in UI and event systems.",
      },
      {
        q: "What is the Strategy pattern?",
        options: [
          "Encapsulating interchangeable algorithms behind an interface",
          "Creating a single instance",
          "Notifying observers",
          "Decorating objects",
        ],
        answer: 0,
        explain: "The Strategy pattern defines a family of algorithms, encapsulates each, and makes them interchangeable. The client selects a strategy at runtime without changing the code that uses it.",
      },
      {
        q: "What is RAII and why is it fundamental in C++?",
        options: [
          "Resource Acquisition Is Initialization: bind resource lifetime to object lifetime",
          "A pattern for sorting",
          "A pattern for networking",
          "A pattern for templates",
        ],
        answer: 0,
        explain: "RAII ties resource acquisition to object construction and release to destruction. When the object goes out of scope, its destructor releases the resource — making leaks and exceptions safe by default.",
      },
      {
        q: "What is the difference between the Factory Method and Abstract Factory patterns?",
        options: [
          "Factory Method uses inheritance to create one product; Abstract Factory creates families of related products",
          "They are identical",
          "Abstract Factory creates one product",
          "Factory Method creates families",
        ],
        answer: 0,
        explain: "Factory Method relies on subclassing to create a single product. Abstract Factory provides an interface to create families of related products without specifying concrete classes.",
      },
      {
        q: "What is the Decorator pattern?",
        options: [
          "Adding behavior to an object dynamically without modifying its class",
          "Creating a single instance",
          "Sorting a collection",
          "Notifying observers",
        ],
        answer: 0,
        explain: "The Decorator pattern wraps an object to add responsibilities dynamically, providing a flexible alternative to subclassing for extending behavior.",
      },
      {
        q: "What is the purpose of the Command pattern?",
        options: [
          "Encapsulating a request as an object, enabling undo/redo and queuing",
          "Creating objects",
          "Managing memory",
          "Sorting data",
        ],
        answer: 0,
        explain: "The Command pattern turns a request into a standalone object, so you can parameterize, queue, log, and undo operations. It is the basis of undo/redo systems.",
      },
      {
        q: "What is the Builder pattern?",
        options: [
          "Constructing complex objects step by step",
          "Creating a single instance",
          "Notifying observers",
          "Decorating objects",
        ],
        answer: 0,
        explain: "The Builder pattern separates the construction of a complex object from its representation, allowing the same construction process to create different representations.",
      },
      {
        q: "What is the Proxy pattern?",
        options: [
          "A placeholder that controls access to another object",
          "A pattern for sorting",
          "A pattern for memory",
          "A pattern for templates",
        ],
        answer: 0,
        explain: "The Proxy pattern provides a surrogate or placeholder for another object to control access, add lazy loading, logging, or access control without changing the real object.",
      },
    ],
    boss: {
      q: "You are building a thread-safe Singleton in C++11. What is the correct, idiomatic implementation?",
      options: [
        "A raw static pointer with manual locking",
        "A function-local static variable (Meyers' Singleton)",
        "A global variable",
        "A static member initialized in the header",
      ],
      answer: 1,
      explain: "The Meyers' Singleton uses a function-local static: 'static Singleton& get() { static Singleton s; return s; }'. In C++11+, local statics are initialized in a thread-safe way, so no explicit locking is needed.",
    },
  },
  {
    id: "interview",
    name: "Interview Q&A",
    icon: "★",
    tagline: "Classic questions and gotchas for a C++ role.",
    color: "#ce93d8",
    questions: [
      {
        q: "What is the difference between a pointer and a reference in C++?",
        options: [
          "A reference must be initialized and cannot be reseated; a pointer can be null and reseated",
          "A pointer must be initialized; a reference can be null",
          "They are identical",
          "References cannot be passed to functions",
        ],
        answer: 0,
        explain: "A reference is an alias that must be initialized and cannot be changed to refer to another object. A pointer can be null, can be reassigned, and requires explicit dereferencing.",
      },
      {
        q: "What is the difference between stack and heap memory?",
        options: [
          "Stack is fast, automatic, limited size; heap is dynamic, manual, larger",
          "Heap is automatic; stack is manual",
          "They are identical",
          "Stack is larger than heap",
        ],
        answer: 0,
        explain: "Stack memory is allocated automatically for local variables, is fast, and has limited size. Heap memory is allocated dynamically (new/malloc), is larger, and must be freed manually (or via smart pointers).",
      },
      {
        q: "What is a memory leak and how do you avoid it in modern C++?",
        options: [
          "Memory not freed; avoid with RAII and smart pointers",
          "Memory freed too early; avoid with raw pointers",
          "A stack overflow",
          "A compile error",
        ],
        answer: 0,
        explain: "A memory leak is allocated memory that is never freed. Modern C++ avoids leaks with RAII and smart pointers (unique_ptr/shared_ptr), which free memory automatically when objects go out of scope.",
      },
      {
        q: "What is the difference between 'new' and 'malloc'?",
        options: [
          "new calls constructors and is type-safe; malloc only allocates raw bytes",
          "malloc calls constructors",
          "They are identical",
          "new is a C function",
        ],
        answer: 0,
        explain: "'new' allocates memory AND calls the constructor, returning a typed pointer. 'malloc' only allocates raw bytes and returns void*. 'new' throws on failure; 'malloc' returns null.",
      },
      {
        q: "What is the difference between 'const' and 'constexpr'?",
        options: [
          "const is runtime constant; constexpr is compile-time constant",
          "They are identical",
          "constexpr is runtime",
          "const is compile-time",
        ],
        answer: 0,
        explain: "'const' means the value cannot be modified after initialization (may be runtime). 'constexpr' guarantees the value is computed at compile time.",
      },
      {
        q: "What is the difference between 'static_cast', 'dynamic_cast', and 'reinterpret_cast'?",
        options: [
          "static_cast: compile-time; dynamic_cast: runtime with RTTI; reinterpret_cast: raw bit reinterpretation",
          "They are identical",
          "dynamic_cast is compile-time",
          "reinterpret_cast is safe",
        ],
        answer: 0,
        explain: "static_cast performs compile-time conversions. dynamic_cast performs runtime checked downcasts (requires RTTI, returns null/fails on wrong type). reinterpret_cast reinterprets the raw bits and is unsafe.",
      },
      {
        q: "What is the difference between a shallow copy and a deep copy?",
        options: [
          "Shallow copies the pointer; deep copies the pointed-to data",
          "Deep copies the pointer only",
          "They are identical",
          "Shallow copy is always safe",
        ],
        answer: 0,
        explain: "A shallow copy copies the pointer value, so two objects share the same data (double-free risk). A deep copy allocates new memory and copies the data, so each object owns its own copy.",
      },
      {
        q: "What is the difference between 'std::array' and a C-style array?",
        options: [
          "std::array is a standard container with size(), bounds-safe access, and STL algorithms",
          "C-style arrays have size()",
          "They are identical",
          "std::array is slower",
        ],
        answer: 0,
        explain: "std::array is a fixed-size container that knows its size, supports iterators and STL algorithms, and can be passed by value. A C-style array decays to a pointer and loses size information.",
      },
      {
        q: "What is the difference between 'std::string' and a C-string (char*)?",
        options: [
          "std::string manages its own memory, knows its length, and is safe; C-strings are null-terminated char arrays",
          "C-strings manage memory automatically",
          "They are identical",
          "std::string is a char array",
        ],
        answer: 0,
        explain: "std::string is a class that manages its own buffer, tracks length, and provides safe operations. A C-string is a null-terminated char array that requires manual management and is prone to buffer overflows.",
      },
      {
        q: "What is the difference between 'std::function' and a raw function pointer?",
        options: [
          "std::function can hold lambdas, functors, and bound functions; a raw pointer only holds a plain function",
          "They are identical",
          "Raw pointers can hold lambdas",
          "std::function is a C function",
        ],
        answer: 0,
        explain: "std::function is a type-erased callable wrapper that can store lambdas, functors, and member functions. A raw function pointer can only point to a plain free function.",
      },
    ],
    boss: {
      q: "You are asked to design a class that owns a heap buffer. What must you implement to make it safe and correct?",
      options: [
        "Only a destructor",
        "The Rule of Five: destructor, copy ctor, copy assign, move ctor, move assign",
        "Only a copy constructor",
        "Nothing — the compiler handles it",
      ],
      answer: 1,
      explain: "A class owning a heap buffer must follow the Rule of Five: a destructor to free memory, copy constructor and copy assignment for deep copies, and move constructor and move assignment for efficient transfers. Otherwise you get double-frees or leaks.",
    },
  },
];
